using System.Collections.Generic;
using System.Linq;

namespace CommandLineParsing.Tests.RandomNames
{
    public static class NameService
    {
        #region A CSV string with names and genders

        private static readonly string _names =

@"Roxann,Ruppe,F
Kara,Rolling,F
Noelle,Mirarchi,F
Janey,Calcagno,F
Silvia,Proffit,F
Tennie,Steadham,F
Alecia,Mandez,F
Daria,Denise,F
Shan,Mercure,F
Chanel,Niswonger,F
Sherlyn,Swims,F
Yolando,Jeppesen,F
Quincy,Syed,M
Beverly,Hash,F
Tova,Raasch,F
Mira,Iliff,F
Vernell,Stowell,F
Jodi,Williamson,F
Abel,Northup,M
Melany,Hurlburt,F
Danita,Spratling,F
Theron,Clingerman,M
Floy,Sweitzer,F
Larisa,Lydick,F
Nannie,Corl,F
Nikki,Naylor,F
Madonna,Zakrzewski,F
Trevor,Ybarra,M
Blanch,Bartkowski,F
Marhta,Wegner,F
Asha,Riemer,F
Keturah,Godard,F
Madeline,Esslinger,F
Mohammad,Rutt,M
Sophie,Junk,F
Juliana,Valenta,F
Tiana,Depue,F
Chieko,Condrey,F
Esmeralda,Neuendorf,F
Ofelia,Meneely,F
Mariette,Kimbro,F
Jasmin,Hillis,F
Flo,Coltrane,F
Chandra,Mckeever,F
Garnet,Telles,F
Rosina,Mosqueda,F
Angella,Sutterfield,F
Marcy,Giesen,F
Mercy,Withrow,F
Lanora,Gilmartin,F
Meaghan,Dicks,F
Tona,Hippe,F
Ulrike,Murphey,F
Magaret,Pankow,F
Latoyia,Mineau,F
Alfreda,Muck,F
Gladis,Flavell,F
Kareen,Fowles,F
Jenna,Murff,F
Brunilda,Cannata,F
Stormy,Crossno,F
Alexander,Kranz,M
Marietta,Knowles,F
Johna,Ahn,F
Isabel,Winkelman,F
Rudy,Harty,M
Lula,Frei,F
America,Insley,F
Liza,Gard,F
Parker,Sowders,M
Jessie,Avalos,M
Signe,Wald,F
Cliff,Schaeffer,M
Claretha,Shetley,F
Marcos,Uy,M
Terrance,Cabell,M
Angelyn,Hillebrand,F
Albertha,Kunkle,F
Melania,Snider,F
Denver,Mckellar,M
Dwight,Vanzile,M
Alicia,Luis,F
Felipa,Chamber,F
Fallon,Perron,F
Shaquita,Ericsson,F
Frankie,Navas,M
Earnestine,Colgan,F
Clay,Weinman,M
Trang,Pender,F
Yevette,Chiang,F
Julee,Curnutt,F
Carol,Fiedler,M
Henry,Grau,M
Georgiana,Moise,F
Alfredia,Walrath,F
Danyelle,Potts,F
Greta,Epps,F
Chastity,Grissom,F
Natasha,Muldrew,F
Ida,Deforge,F
Gudrun,Lisa,F
Clarisa,Caywood,F
Lannie,Sayler,F
Lashaunda,Bott,F
Jeanelle,Ambler,F
Irina,Santangelo,F
Willie,Huggins,M
Cletus,Heitzman,M
Alfredo,Wiliams,M
Colton,Fouse,M
Marlen,Monica,F
Tamie,Faircloth,F
Violet,Tijerina,F
Flavia,Hersh,F
Thalia,Anselmo,F
Marylynn,Heart,F
Alma,Ronquillo,F
Alfonzo,Fernald,M
Caitlin,Chain,F
Zenobia,Woolard,F
Sherika,Dingman,F
Hugo,Methvin,M
Brain,Sprvill,M
Reyna,Eckman,F
Leia,Myers,F
Agnes,Harpster,F
Gerard,Henson,M
Karlene,Hofman,F
Tobias,Gulotta,M
Florinda,Wiggs,F
Verla,Sparano,F
Awilda,Vanhook,F
Deangelo,Mundt,M
Mittie,Chery,F
Fatimah,Rosenbalm,F
Lincoln,Hofmann,M
Beulah,Kempf,F
Eugenio,Mortellaro,M
Bette,Simoneau,F
Phung,Delcastillo,F
Windy,Ing,F
Marcelina,Haught,F
Glenda,Larrabee,F
Juliet,Brennen,F
Gale,Kipp,M
Evelyne,Crim,F
Nguyet,Flagler,F
Millie,Trexler,F
Wai,Mcentee,F
Sharolyn,Boehmer,F
Michell,Spada,F
Stephenie,Connell,F
Annmarie,Sass,F
Romana,Anwar,F
Hayley,Parkhurst,F
Wilson,Christ,M
Chassidy,Danis,F
Norma,Geddes,F
Myrtle,Anson,F
Chante,Crass,F
Norbert,Swigert,M
Hilario,Kantz,M
Priscilla,Charon,F
Isidra,Yin,F
Leonida,Nickols,F
Alexandria,Dupras,F
Elene,Orourke,F
Justa,Arrington,F
Laveta,Sligh,F
Brice,Koval,M
Diego,Stonerock,M
Jonelle,Ernst,F
Mozelle,Yaple,F
Mahalia,Alfonso,F
Keila,Arnold,F
Shavon,Castro,F
Chin,Bassin,F
Dagmar,Colson,F
Carlene,Rudie,F
Maude,Runk,F
Donetta,Bassett,F
Jackeline,Lovings,F
Lorilee,Burbage,F
Shonda,Revell,F
Isaiah,Taggert,M
Jessi,Garrido,F
Celesta,Christy,F
Emily,Landrith,F
Monica,Hille,F
Tory,Goldschmidt,M
Yu,Welles,F
Timika,Muro,F
Chau,Cornforth,F
Corine,Mcpeak,F
Veronique,Copeland,F
Elinore,Irizarry,F
Tori,Quirk,F
Charlsie,Trinidad,F
Cristin,Paoletti,F
Corinne,Pfannenstiel,F
Jenifer,Dusseault,F
Donette,Ketron,F
Kathi,Naslund,F
Barrett,Bode,M
Natosha,Trujillo,F
Lizzette,Dworkin,F
Isaura,Pummill,F
Tyree,Jeanlouis,M
Owen,Heyward,M
Adriene,Nickson,F
Edith,Knopp,F
Carline,Zucker,F
Cyndi,Baranowski,F
Hye,Delay,F
Gertrud,Guan,F
Stewart,Napier,M
Celsa,Primrose,F
Kit,Stanton,F
Buddy,Pellett,M
Monte,Hachey,M
Merissa,Baugher,F
Willard,Roman,M
Myung,Eccleston,F
Claudine,Krahn,F
Elvie,Jacome,F
Fiona,Culbreth,F
Araceli,Fava,F
Kasey,Krick,M
Hosea,Starkes,M
Woodrow,Moffat,M
Rogelio,Desrosiers,M
Jim,Hemphill,M
Pauletta,Crawley,F
Chrystal,Whitlatch,F
Judson,Bickers,M
Lauryn,Bowland,F
Ricardo,Juan,M
Despina,Audie,F
Hazel,Gillespie,F
Vi,Villela,F
Errol,Hurston,M
Wilfredo,Gardener,M
Sabina,Mayse,F
Refugia,Garlow,F
Summer,Sprau,F
Yukiko,Mayhew,F
Marjorie,Valverde,F
Jaunita,Seibert,F
Edyth,Culligan,F
Ronni,Vanegas,F
Enedina,Goree,F
Natalia,Lung,F
Shirly,Herford,F
Kaye,Knappenberger,F
Zulma,Muse,F
Ashly,Partlow,F
Loyce,Meng,F
Janett,Rogerson,F
Oscar,Tilson,M
Catherin,Stahl,F
Domenica,Rishel,F
Enriqueta,Dan,F
Lai,Craddock,F
Krystal,Mestas,F
Jesica,Harju,F
Shirleen,Gainer,F
Earlean,Rady,F
Diana,Thurmon,F
Wilda,Garmany,F
Brigette,Rotter,F
Shayne,Summers,M
Janita,Krikorian,F
Dara,Bergan,F
Ryann,Bradberry,F
Nolan,Barbagallo,M
Josie,Calfee,F
Beatriz,Mcmichael,F
Felecia,Mullan,F
Gonzalo,Bellew,M
Dierdre,Sack,F
Tosha,Brungardt,F
Elvin,Raleigh,M
Bell,Desantiago,F
Blair,Pehrson,M
Lyndia,Blahnik,F
Patrick,Reeder,M
Laurel,Gott,F
Andres,Kravetz,M
Shu,Gosha,F
Arletha,Emmons,F
Harrison,Ostlund,M
Mel,Pasquale,M
Margeret,Ryer,F
Hildred,Herman,F
Danyell,Berndt,F
Syreeta,Laviolette,F
Melanie,Winston,F
Venita,Varnum,F
Tamar,Bowes,F
Oleta,Veiga,F
Sudie,Fierros,F
Ali,Fullington,M
Alona,Scuderi,F
Layla,Cervantes,F
Chuck,Daniels,M
Charlene,Filson,F
June,Samet,F
Jayson,Willcox,M
Deandrea,Redrick,F
Hayden,Rahm,M
Demetra,Holloman,F
Lennie,Lafever,F
Audrie,Straley,F
Makeda,Masten,F
Nereida,Cabezas,F
Kai,Mickles,F
Shauna,Junior,F
Alise,Dees,F
Britt,Highfield,M
Lovella,Rozman,F
Lajuana,Abernathy,F
Jennifer,Archambault,F
Sharda,Corby,F
Coreen,Canty,F
Magnolia,Candelario,F
Rayford,Bouknight,M
Claretta,Naughton,F
Leonia,Kuhns,F
Evelina,Mcnamee,F
Malia,Heras,F
France,Suhr,F
Zola,Pettit,F
Wendolyn,Salguero,F
Kimberli,Gallo,F
Larue,Hefley,F
Lucrecia,Herren,F
Denisse,Peace,F
Nelida,Arbogast,F
Eileen,Masse,F
Kristle,Shafer,F
Sage,Schumaker,F
Martine,Hartline,F
Alvaro,Montoya,M
Greg,Leicht,M
Katherine,Digirolamo,F
Karma,Mckean,F
Betsey,Wachtel,F
Laraine,Wickersham,F
Daren,Dominguez,M
Hope,Cassel,F
Ethelene,Adolphsen,F
Nanci,Maysonet,F
Jutta,Correia,F
Burt,Poisson,M
Nathanael,Zingaro,M
Eufemia,Jenny,F
Kaitlyn,Pickle,F
Tommie,Rick,M
Annamaria,Perlmutter,F
Adelle,Toro,F
Cordelia,Branstetter,F
Larraine,Lapoint,F
Dixie,Eggen,F
Francie,Heck,F
Ela,Hurtt,F
Sherrie,Heyden,F
Ladonna,Lipinski,F
Angeles,Hypes,F
Izola,Edlin,F
Clarissa,Schlemmer,F
Babette,Brass,F
Renita,Peri,F
Fredric,Hitchman,M
Freddie,Coberly,M
Erinn,Fergus,F
Dionne,Downer,F
Issac,Gayhart,M
Regenia,Prevost,F
Jake,Cuccia,M
Eloisa,Preslar,F
Kassie,Slankard,F
Dirk,Otto,M
Julius,Alejo,M
Tambra,Vanasse,F
Mireille,Mundell,F
Colleen,Mehta,F
Ileen,Curatolo,F
Deonna,Loiacono,F
Adah,Zurcher,F
Wally,Guarnieri,M
Joyce,Bizzell,F
Traci,Deshields,F
Kitty,Dahn,F
Naida,Dreher,F
Mindy,Delorenzo,F
Catrice,Drager,F
Lanette,Ferrier,F
Michaela,Hazlitt,F
Consuelo,Bramer,F
Maribeth,Jahnke,F
January,Sherrard,F
Josefine,Malo,F
Chloe,Rosenthal,F
Emelia,Beringer,F
Emilia,Bahe,F
Suzanne,Pitt,F
Oliva,Orndorff,F
Corliss,Garey,F
Beckie,Aguon,F
Shea,Hasler,F
Edmund,Reichenbach,M
Ariane,Manalo,F
Murray,Carlo,M
Jeffery,Knauf,M
Sandi,Swingle,F
Wynell,Hopper,F
Florencia,Slough,F
Efren,Sais,M
Lucien,Taber,M
Eugenie,Bellantoni,F
Hortense,Demps,F
Meggan,Tierney,F
Dorine,Shambo,F
Abbie,Liefer,F
Tomas,Blagg,M
Carri,Chard,F
Janette,Brim,F
Staci,Tardugno,F
Cristal,Gillison,F
Letitia,Mechling,F
Thi,Doyle,F
Miyoko,Hatt,F
Aida,Ollis,F
Elissa,Burcham,F
Lashawnda,Sledge,F
Susy,Rosell,F
Evan,Nadel,M
Sha,Laubscher,F
Darlene,Knowlton,F
Allen,Ritch,M
Gracie,Goza,F
Brock,Villano,M
Sergio,Chirico,M
Nikole,Herrmann,F
Rosalva,Kingman,F
Elroy,Craner,M
Kristan,Natali,F
Garth,Anzaldua,M
Sanda,Settles,F
Maudie,Maniscalco,F
Soon,Abele,F
Laverne,Bouldin,M
Kaylene,Schuelke,F
Eleanora,Murrieta,F
Samual,Mullenix,M
Simona,Mcmillon,F
Penny,Cruzado,F
Sherrell,Harling,F
David,Schenck,M
Lacey,Meece,F
Shyla,Innocent,F
Michelle,Cranford,F
Mignon,Donlon,F
Zoe,Zellars,F
Maryrose,Dever,F
Emory,Stefani,M
Armanda,Quinteros,F
Angelic,Brandow,F
Hugh,Lippman,M
Zula,Work,F
Yoko,Schartz,F
Orpha,Gin,F
Serina,Santee,F
Simonne,Ratcliff,F
Yelena,Cornish,F
Lashanda,Mulligan,F
Scott,Osuna,M
Iola,Rezendes,F
Steve,Yan,M
Arlene,Mims,F
Andree,Kieser,F
Sophia,Stickney,F
Ladawn,Guynes,F
Hedy,Quach,F
Celina,Parfait,F
Tracie,Brandt,F
Sandee,Melo,F
Genevieve,Honey,F
Lorette,Martine,F
Margarete,Sato,F
Jorge,Comfort,M
Joy,Morley,F
Ola,Mcchristian,F
Thaddeus,Autrey,M
Roman,Addison,M
Yuriko,Courtney,F
Randolph,Carrillo,M
Tu,Freudenburg,F
Vonnie,Cosey,F
Joella,Melder,F
Emogene,Shanks,F
Layne,Hussein,F
Merlene,Round,F
Merrill,Pickles,M
Brigida,Macneil,F
Danny,Janousek,M
Debera,Kennington,F
Damion,Bullen,M
Lolita,Cushman,F
Kieth,Gomez,M
Maxwell,Gaffney,M
Donte,Tarpley,M
Wilfred,Rencher,M
Shani,Quayle,F
Maira,Rana,F
Jack,Baucom,M
Trent,Arechiga,M
Milda,Bale,F
Anjanette,Post,F
Kindra,Fritsche,F
Tresa,Henshaw,F
Gaylord,Hebel,M
Bobbye,Martindale,F
Samira,Ettinger,F
Florida,Kriss,F
Brandi,Leming,F
Myrle,Weatherhead,F
Columbus,Hamernik,M
Darren,Halligan,M
Maida,Oreilly,F
Olympia,Esper,F
Carmon,Capella,F
Sonja,Libbey,F
Tara,Callery,F
Nicholle,Matheney,F
Eliseo,Azure,M
Cheryl,Rutigliano,F
Mitsuko,Beekman,F
Maurine,Decelles,F
Monserrate,Schuetz,F
Albina,Beard,F
Lasandra,Puett,F
Marisol,Freiberg,F
Denis,Elie,M
Margarite,Ogan,F
Merilyn,Elza,F
Vanita,Aurand,F
Elba,Gift,F
Tonita,Prunty,F
Aracelis,Mccutcheon,F
Otha,Alatorre,M
Bao,Yearwood,F
Juliette,Ridgell,F
Ashlie,Mazzella,F
Kirby,Karns,M
Louis,Philyaw,M
Jannette,Garnett,F
Janee,Stainback,F
Felica,Messick,F
Christeen,Iversen,F
Dinah,Dagley,F
Krista,Rine,F
Carlota,Carruth,F
Danial,Legrande,M
Romeo,Gast,M
Annamae,Miracle,F
Cleora,Gehl,F
Eulah,Broach,F
Antoinette,Martz,F
Rhea,Ruppert,F
Jenise,Middendorf,F
Dollie,Wren,F
Darcie,Szymanski,F
Aimee,Pinnock,F
Tobi,Lowell,F
Maye,Monks,F
Star,Cheatam,F
Rosamond,Sharman,F
Bulah,Carino,F
Carita,Calles,F
Morton,Wainright,M
Shelia,Sigala,F
Heike,Ladner,F
Philip,Widmer,M
Helga,Youssef,F
Kellie,Studley,F
Harriette,Demelo,F
Jan,Greenwell,M
Velvet,Kosak,F
Renate,Lattimore,F
Carli,Reising,F
Saran,Wint,F
Adelaida,Kimber,F
Melba,Dull,F
Darline,Blas,F
Arturo,Glatt,M
Verdie,Owsley,F
Samantha,Langlois,F
Marcella,Running,F
Andria,Dobyns,F
Janine,Negrete,F
Truman,Dolphin,M
Darcy,Oleary,F
Cammie,Rominger,F
Elayne,Gallop,F
Sandra,Stmarie,F
Mable,Damm,F
Louisa,Hamann,F
Rosalba,Mae,F
Linnie,Word,F
Oralia,Weathers,F
Junko,Cossette,F
Genna,Bea,F
Ayana,Jude,F
Darryl,Cardillo,M
Emmanuel,Voges,M
Ivette,Blatter,F
Matthew,Southard,M
Johana,Borror,F
Vella,Crater,F
Arielle,Brannan,F
Elina,Leleux,F
Tawanda,Moriarty,F
Carmine,Bunger,M
Marion,Mleczko,M
Stefany,Baldree,F
Donita,Randle,F
Arcelia,Lyles,F
Sharla,Pinero,F
Rochelle,Dick,F
Agustina,Tippins,F
Tracee,Mosely,F
Macie,Reza,F
Benedict,Mcelhaney,M
Mike,Im,M
Yun,Woolsey,F
Keven,Sword,M
Sharon,Curran,F
Racheal,Jarboe,F
Novella,Toews,F
Gino,Leist,M
Antwan,Maugeri,M
Minerva,Nowlin,F
Luz,Sauls,F
Dorathy,Laboy,F
Lucienne,Chong,F
Deirdre,Hisle,F
Stephany,Dorsch,F
Jeanine,Rollins,F
Cristie,Simser,F
Delbert,Swint,M
Donnetta,Daniele,F
Abbey,Zertuche,F
Jesenia,Mingle,F
Mellissa,Hoose,F
Diedre,Schorn,F
Collen,Clothier,F
Cassy,Hy,F
Daniella,Tyra,F
Karry,Morrissey,F
Daniell,Burdge,F
Delcie,Aldana,F
Roberto,Ellingsworth,M
Melaine,Raggs,F
Allene,Eckert,F
Adolfo,Mariano,M
Mendy,Bernabe,F
Catalina,Millspaugh,F
Dino,Christensen,M
Ranee,Vincelette,F
Delpha,Tregre,F
Tyron,Pane,M
Marketta,Denver,F
Jeraldine,Ezell,F
Mandi,Truesdell,F
Hoyt,Noah,M
Christal,Chiasson,F
Francesco,Rodiguez,M
Wei,Dimaio,F
Anya,Kula,F
Kimberely,Balicki,F
Delila,Ebel,F
Antonetta,Recinos,F
Luana,Strittmatter,F
Hung,Dublin,M
Corrin,Arp,F
Annie,Puckett,F
Hector,Mahle,M
Avelina,Brion,F
Clare,Solem,F
Retta,Beaupre,F
Mitchell,Henkel,M
Hobert,Menendez,M
Lashandra,Secor,F
Britta,Bosh,F
Maritza,Roysden,F
Rosalind,Pardue,F
Delinda,Duquette,F
Amos,Tores,M
Lynn,Sykora,M
Rupert,Bogen,M
Elizbeth,Hermanson,F
Dorethea,Steffensmeier,F
Jacelyn,Niswander,F
Caryl,Cassity,F
Letty,Balog,F
Min,Connors,F
Lane,Kendrick,M
Shawn,Sickler,M
Kerri,Hug,F
Sidney,Sheller,M
Fred,Wolak,M
Kristal,Averett,F
Giovanni,Leet,M
Loris,Mahn,F
Hiram,Ulrich,M
Elliot,Durgan,M
Filiberto,Journey,M
Torrie,Paiva,F
Deloris,Diehl,F
Grace,Deleo,F
Sheryll,Isbell,F
Dominick,Oser,M
Edris,Hanel,F
Katlyn,Thong,F
Lyn,Almendarez,F
Hal,Rathke,M
Karan,Bradford,F
Pamila,Dupree,F
Xiomara,Spoto,F
Samatha,Burson,F
Doreatha,Darrington,F
Inger,Hsieh,F
Omar,Volkert,M
Alyssa,Ryant,F
Dennis,Benitez,M
Fredrick,Roque,M
Len,Birden,M
Isaac,Zayas,M
Cherish,Orta,F
Garrett,Hoppe,M
Dinorah,Halper,F
Stephania,Kornreich,F
Louetta,Basler,F
Veola,Zermeno,F
Effie,Proehl,F
Otto,Seals,M
Benton,Whiteford,M
Song,Truett,F
Jinny,Denniston,F
Katheleen,Grooms,F
Jacinda,Cahoon,F
Rema,Tee,F
Celine,Gagnier,F
Milo,Maciel,M
Lamar,Marti,M
Mandie,Muir,F
Waneta,Segrest,F
Thao,Norvell,F
Carlyn,Chiu,F
Shayna,Pica,F
Keeley,Finley,F
Charles,Hogg,M
Fonda,Helget,F
Nancee,Laurel,F
Kristeen,Modeste,F
Clarita,Klimas,F
Nickole,Stelle,F
Charline,Karney,F
Tenisha,Simard,F
Kam,Whitlow,F
Natisha,Tolan,F
Will,Marney,M
Bong,Vicini,F
Jeanette,Gorham,F
Sonny,Galey,M
Latasha,Swindell,F
Magen,Steakley,F
Chi,Hoots,M
Scarlett,Grasser,F
Agueda,Turnbull,F
Vaughn,Lechler,M
Yael,Rushing,F
Lia,Bornstein,F
Livia,Friscia,F
Suellen,Vanfleet,F
Marvis,Stich,F
Melva,Cassara,F
Gavin,Primmer,M
Elke,Hillary,F
Verdell,Pennypacker,F
Zackary,Bufkin,M
Dann,Dessert,F
Danica,Helberg,F
Michiko,Tovar,F
Sommer,Sthilaire,F
Wm,Mazzone,M
Le,Kahle,F
Sondra,Favreau,F
Felice,Pough,F
Eliana,Vicknair,F
Jeana,Paz,F
Brady,Matter,M
Tammie,Isaac,F
Nelson,Lenihan,M
Sharri,Mullenax,F
Arlette,Malan,F
Larhonda,Santa,F
Julianna,Connelly,F
Erika,Weiler,F
Boyce,Munger,M
Charlena,Leahy,F
Sari,Prada,F
Emmitt,Stenzel,M
Charmain,Hussey,F
Trudie,Giefer,F
Kenia,Terhaar,F
Jessika,Zehnder,F
Nakesha,Hennessee,F
Aubrey,Helms,M
Marisela,Zeigler,F
Maria,Scheffel,M
Kay,Lowrey,F
Frank,Blust,M
Alycia,Cloud,F
Sixta,Ganley,F
Delma,Helm,F
Thu,Chisum,F
Kaley,Kelson,F
Noella,Tao,F
Jerold,Kinoshita,M
Matt,Mealy,M
Ginger,Kugel,F
Louise,Lo,F
Claire,Prime,F
Concepcion,Drone,F
Gaylene,Sheroan,F
Jc,Mencer,M
Ilse,Caulder,F
Otis,Fierro,M
Lilli,Bunge,F
Arden,Rosenbeck,M
Rosann,Forcier,F
Sydney,Andresen,M
Kizzie,Bixby,F
Belkis,Cantin,F
Cinderella,Yawn,F
Breanne,Hillyard,F
Darius,Marable,M
Gwyneth,Pedroso,F
Gus,Boyster,M
Quiana,Meas,F
Lesa,Cheslock,F
Nicol,Zufelt,F
Katharina,Wooden,F
Katia,Hanus,F
Carissa,Dwight,F
Tamela,Ferry,F
Lilian,Fontana,F
Vanda,Kinard,F
Domenic,Platner,M
Carmela,Justiniano,F
Sandie,Hossain,F
Jeannine,Lefebvre,F
Hermine,Standard,F
Teresa,Peugh,F
Antonia,Lambson,M
Dannielle,Beardsley,F
Bibi,Brockwell,F
Antionette,Favela,F
Javier,Berk,M
Marivel,Wansley,F
Randi,Conroy,F
Vertie,Speaks,F
Mercedez,Hawker,F
Shalon,Mcconkey,F
Ayanna,Cushenberry,F
Janeen,Galle,F
Wava,Bronstein,F
Heidi,Ballengee,F
Caterina,Regalado,F
Odilia,Daigneault,F
Miki,Hensen,F
Shantae,Adkisson,F
Roscoe,Gittens,M
Deborah,Mantilla,F
Charisse,Ruder,F
Nannette,Runner,F
Jeneva,Artrip,F
Kia,Claggett,F
Lydia,Fucci,F
Elfreda,Onken,F
Carmelina,Olberding,F
Voncile,Mcgavock,F
Bessie,Singleterry,F
Delsie,Heilman,F
Dusti,Mitschke,F
Venus,Donoghue,F
Michel,Farver,M
Suk,Dooley,F
Terry,Breault,M
Dian,Maroon,F
Loren,Cianci,M
Ena,Mena,F
Brinda,Rado,F
Melani,Caryl,F
Therese,Boykin,F
Clementine,Gardella,F
Monnie,Lehrer,F
Jeanie,Gudger,F
Lorrine,Pauls,F
Elyse,Updike,F
Hue,Faye,F
Lanell,Panther,F
Tammi,Pasko,F
Robbin,Bonnette,F
Perry,Poland,M
Drucilla,Heider,F
Marybelle,Sitz,F
Ward,Mckeller,M
Mellie,Dewald,F
Chae,Hagwood,F
Cecilia,Oliphant,F
Maximo,Despain,M
Lorelei,Kinnard,F
Julissa,Colucci,F
Matilda,Slabaugh,F
Lera,Mcgillivray,F
Louvenia,Poulton,F
Karissa,Dufner,F
Merle,Rosenblatt,M
Humberto,Levins,M
Robbi,Buckle,F
Cindi,Holder,F
Marlin,Rieth,M
Gabriele,Knipp,F
Debra,Mumford,F
Renato,Carabajal,M
Stacey,Montalvo,M
Melodi,Gershman,F
Faustina,Hutson,F
Shanae,Hebert,F
Caridad,Mckee,F
Ashli,Joynes,F
Velva,Bruggeman,F
Jodie,Standifer,F
Cyrstal,Ohare,F
Syble,Points,F
Lea,Kesten,F
Victorina,Narciso,F
Jamaal,Doner,M
Brittanie,Scharf,F
Loretta,Stromberg,F
Timothy,Chamberlain,M
Cheyenne,Torrain,F
Eli,Agrawal,M
Pedro,Duden,M
Manda,Fontes,F
Clifton,Seger,M
Harold,Catanzaro,M
Myra,Estill,F
Lucie,Treiber,F
Phyliss,Barriere,F
Lori,Goodreau,F
Deon,Hammock,M
Deandra,Lemen,F
Denisha,Trott,F
Cecille,Loos,F
Aide,Canada,F
Madaline,Cawthorne,F
Dalton,Lacomb,M
Jillian,Busey,F
Blanca,Bergquist,F
Waltraud,Higuchi,F
Mollie,Masden,F
Sharilyn,Mathis,F
Maisie,Posada,F
Marquetta,Godwin,F
Delisa,Snowball,F
Valrie,Shadduck,F
Flor,Forth,F
Rachell,Tudor,F
Carlie,Boulanger,F
Chantel,Gu,F
Leon,Hannon,M
Ila,Harley,F
Ariel,Straight,M
Wen,Filippini,F
Rubie,Gotto,F
Alexis,Kissell,M
Dominque,Debellis,F
Damian,Wooley,M
Marylee,Bran,F
Basilia,Shum,F
Ashlyn,Salgado,F
Brent,Mcgarrah,M
Ludivina,Schoepp,F
Moses,Mulkey,M
Marianela,Blakeslee,F
Georgeann,Reiner,F";

#endregion

        public static IEnumerable<Name> Get()
        {
            return _names.Replace("\r", "").Split("\n").Select(ParseCSV);
        }

        private static Name ParseCSV(string line)
        {
            var parts = line.Split(',');

            return new Name
            (
                firstname: parts[0],
                lastname: parts[1],
                gender: parts[2] == "F" ? Genders.Female : Genders.Male
            );
        }
    }
}
